### ISSUE TITLE
Markdown editor, should take up full width and height

### ISSUE THREAD

**Issue by raghav-wd** [vivekweb2013/gitnoter#47]
## Current UI
![image](https://user-images.githubusercontent.com/41248639/166093554-2d82e596-465e-482a-9b47-7ed2ee9935f9.png)

## Proposed UI
![image](https://user-images.githubusercontent.com/41248639/166093957-6b65c886-9a1d-4f52-a78e-c61e2ec1ec73.png)

## Why?
Since, the sole purpose of application is to take notes (usually few pages long), the 'Proposed UI' provides a better view to user when editing and previewing those changes.

#### Notes
I've excludes other UI components in 'Proposed UI' like  'Path', 'Note Name' and 'Cancel/Save' button, they should obviously be there.

**Comment by vivekweb2013** [comment]
Agree. I did not know that the editor view looks this small on high resolution screens. Thanks for opening the issue. Would you like to work on this? or shall I take this one.

**Comment by raghav-wd** [comment]
Give me this week's time, I'll try to do it. I need to know do I have to run backend as well to make the mentioned changes?

**Comment by vivekweb2013** [comment]
> Give me this week's time, I'll try to do it. I need to know do I have to run backend as well to make the mentioned changes?

Sure, take your time. Yes the backend needs to be started in order to access editor view in frontend. Please refer the readme file from backend folder. 

I'm now feeling that starting backend for just the frontend changes would be an overhead. Please give me some time to check if I can remove this pre-requisite using some proxy or something...

I'll keep you posted in this thread.

**Comment by raghav-wd** [comment]
Sure, thanks for your efforts!

**Comment by vivekweb2013** [comment]
@raghav-wd I've added the steps to run frontend app without running backend module locally. The trick is to use staging api-server instead of starting and using the local backend server.

Please refer - https://github.com/vivekweb2013/gitnoter/tree/main/frontend#running-the-frontend-module-locally

Let me know if you face any issues. I'd appreciate your contribution to this project.

**Comment by raghav-wd** [comment]
Hey, I was able to run the frontend, but there's this issue with `github oauth` when trying to login

![image](https://user-images.githubusercontent.com/41248639/166110348-de1ea24c-2495-436d-9936-2dbfaa22935d.png)

**Comment by vivekweb2013** [comment]
> Hey, I was able to run the frontend, but there's this issue with `github oauth` when trying to login

Fixed. Please try now. The staging db was down for some reason. I've fixed it now. Please try and let me know if it still doesn't work.

**Comment by vivekweb2013** [comment]
Thanks @raghav-wd for the contribution.
The changes are deployed to production. [See here](https://github.com/vivekweb2013/gitnoter/actions/runs/2252743778)
